Default: &defaults
  database: yesod-tutorial.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-tutorial_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-tutorial_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-tutorial_production.sqlite3
  poolsize: 100
  <<: *defaults
